#########################################################
#### Variables
#########################################################

@subscriptionId = [your-subscription-id]
@resourceGroup = [your-resource-group-name]
@storeName = [your-store-name]
@armBaseUrl = https://management.azure.com/subscriptions
@storesPath = {{armBaseUrl}}/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.Token/stores
@version = ?api-version=2018-08-01-preview
@serviceName = testService
@tokenName = testToken
@policyName = testPolicy

#########################################################
###### List stores
#########################################################
 
GET {{storesPath}} 
    {{version}}
Authorization: {{$aadToken}}


#########################################################
###### Create or update store
#########################################################
 
PUT {{storesPath}}/{{storeName}}
    {{version}}
Authorization: {{$aadToken}}
Content-Type: application/json; charset=utf-8

{
    "location": "westcentralus",
    "properties": {
        "authorizedPostRedirectUrls": [
            "http://example.com/tokens/postlogin"
        ]        
    }
}

#########################################################
###### Read store
#########################################################
 
GET {{storesPath}}/{{storeName}}
    {{version}}
Authorization: {{$aadToken}}

#########################################################
###### Delete store
#########################################################
 
DELETE {{storesPath}}/{{storeName}}
    {{version}}
Authorization: {{$aadToken}}

#########################################################
###### List services
#########################################################
 
GET {{storesPath}}/{{storeName}}/services 
    {{version}}
Authorization: {{$aadToken}}


#########################################################
###### Create or update service
#########################################################
 
PUT {{storesPath}}/{{storeName}}/services/{{serviceName}}
    {{version}}
Authorization: {{$aadToken}}
Content-Type: application/json; charset=utf-8

{
  "properties": {
    "authentication": {
      "managedIdentityProvider": {
        "name": "dropbox"
      },
      "parameters": {
        "clientid": "[your-dropbox-client-id]",
        "clientsecret": "[your-dropbox-client-secret]"
      }
    },
    "displayName": "{{serviceName}}"
  }
}

#########################################################
###### Read service
#########################################################
 
GET {{storesPath}}/{{storeName}}/services/{{serviceName}}
    {{version}}
Authorization: {{$aadToken}}


#########################################################
###### Delete service
#########################################################
 
DELETE {{storesPath}}/{{storeName}}/services/{{serviceName}}
    {{version}}
Authorization: {{$aadToken}}


#########################################################
###### List tokens
#########################################################
 
GET {{storesPath}}/{{storeName}}/services/{{serviceName}}/tokens 
    {{version}}
Authorization: {{$aadToken}}

#########################################################
###### Create or update token
#########################################################
 
PUT {{storesPath}}/{{storeName}}/services/{{serviceName}}/tokens/{{tokenName}}
    {{version}}
Authorization: {{$aadToken}}
Content-Type: application/json; charset=utf-8

{
  "properties": {
    "displayName": "{{tokenName}}"
  }
}

#########################################################
###### Read token
#########################################################
 
GET {{storesPath}}/{{storeName}}/services/{{serviceName}}/tokens/{{tokenName}}
    {{version}}
Authorization: {{$aadToken}}

#########################################################
###### Delete token
#########################################################
 
DELETE {{storesPath}}/{{storeName}}/services/{{serviceName}}/tokens/{{tokenName}}
    {{version}}
Authorization: {{$aadToken}}

#########################################################
###### List access policies
#########################################################

GET {{storesPath}}/{{storeName}}/accessPolicies
    {{version}}
Authorization: {{$aadToken}}

#########################################################
###### Get access policy
#########################################################

GET {{storesPath}}/{{storeName}}/accessPolicies/{{policyName}}
    {{version}}
Authorization: {{$aadToken}}

#########################################################
###### Create or update access policy
#########################################################

PUT {{storesPath}}/{{storeName}}/accessPolicies/{{policyName}}
    {{version}}
Authorization: {{$aadToken}}
Content-Type: application/json; charset=utf-8

{  
  "properties": {
    "name": "{{policyName}}",
    "principal": {
      "tenantId": "[your-tenant-id]",
      "objectId": "[your-object-id]"
    },
    "permissions": ["Get", "List", "CreateOrUpdate", "Delete"]
  }
}

#########################################################
###### Patch access policy
#########################################################

PATCH {{storesPath}}/{{storeName}}/accessPolicies/{{policyName}}
    {{version}}
Authorization: {{$aadToken}}
Content-Type: application/json; charset=utf-8

{
    "properties": {
        "name" : "{{policyName}}",
        "principal": {
            "tenantId": "[your-tenant-id]",
            "objectId": "[your-object-id]"
        },
        "permissions": ["Get", "List", "CreateOrUpdate", "Delete"]
    }
}

#########################################################
###### Delete access policy
#########################################################

DELETE {{storesPath}}/{{storeName}}/accessPolicies/{{policyName}}
    {{version}}
Authorization: {{$aadToken}}
