#########################################################
#### Variables
#########################################################

@subscriptionId = [your-subscription-id]
@resourceGroup = [your-resource-group-name]
@storeName = [your-store-name]
@serviceName = testService
@tokenName = testToken
@runtimeBaseUrl = https://{{storeName}}.westcentralus.tokenstore.azure.net

## NOTE: REPLACE [your-domain.com] WITH YOUR DOMAIN NAME. For example if your personal user Id is me@mycompany.com,
## the string [your-domain.com] should be replaced with mycompany.com everywhere in this document

#########################################################
###### Read token
#########################################################

GET {{runtimeBaseUrl}}/services/{{serviceName}}/tokens/{{tokenName}}
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}

#########################################################
###### List tokens
#########################################################

GET {{runtimeBaseUrl}}/services/{{serviceName}}/tokens
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}


#########################################################
###### Get token
#########################################################

POST {{runtimeBaseUrl}}/services/{{serviceName}}/tokens/{{tokenName}}
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}

#########################################################
###### Get access token
#########################################################

POST {{runtimeBaseUrl}}/services/{{serviceName}}/tokens/{{tokenName}}/accesstoken
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}

#########################################################
###### Save token using redirect code
#########################################################

POST {{runtimeBaseUrl}}/services/{{serviceName}}/tokens/{{tokenName}}/save
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}
Content-Type: application/json; charset=utf-8

{ "code" : "" }

#########################################################
###### List services
#########################################################

GET {{runtimeBaseUrl}}/services
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}

#########################################################
###### Read service
#########################################################

GET {{runtimeBaseUrl}}/services/{{serviceName}}
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}


#########################################################
###### Create or update service
#########################################################
 
PUT {{runtimeBaseUrl}}/services/{{serviceName}}
Authorization: {{$aadToken [your-domain.com] aud:https://tokenstore.azure.net}}
Content-Type: application/json; charset=utf-8

{
    "authentication": {
        "managedIdentityProvider": {
            "name": "dropbox"
        },
        "parameters": {
            "clientid": "[your-dropbox-client-id]",
            "clientsecret": "[your-dropbox-client-secret]"
        }
    },
    "displayName": "{{serviceName}}"  
}