#########################################################
#### Variables
#########################################################

@subscriptionId = a39747ec-b5c4-45de-82a1-935083247170
@resourceGroup = nimakkvtest
@vaultName = testVault
@serviceName = testService
@tokenName = testToken
@runtimeBaseUrl = https://{{vaultName}}.westcentralus.tokenvault.azure.net

## NOTE: REPLACE microsoft.com WITH YOUR DOMAIN NAME. For example if your personal user Id is me@mycompany.com,
## the string microsoft.com should be replaced with mycompany.com everywhere in this document

#########################################################
###### Read token
#########################################################

GET {{runtimeBaseUrl}}/services/{{serviceName}}/tokens/{{tokenName}}
Authorization: {{$aadToken microsoft.com aud:https://tokenvault.azure.net}}

#########################################################
###### List tokens
#########################################################

GET {{runtimeBaseUrl}}/services/{{serviceName}}/tokens
Authorization: {{$aadToken microsoft.com aud:https://tokenvault.azure.net}}


#########################################################
###### Get valid access token
#########################################################

POST {{runtimeBaseUrl}}/services/{{serviceName}}/tokens/{{tokenName}}
Authorization: {{$aadToken microsoft.com aud:https://tokenvault.azure.net}}

#########################################################
###### Save token using redirect code
#########################################################

POST {{runtimeBaseUrl}}/services/{{serviceName}}/tokens/{{tokenName}}/save
Authorization: {{$aadToken microsoft.com aud:https://tokenvault.azure.net}}
Content-Type: application/json; charset=utf-8

{ "code" : "" }

# #########################################################
# ###### List services
# #########################################################

# GET {{runtimeBaseUrl}}/services
# Authorization: {{$aadToken microsoft.com aud:https://tokenvault.azure.net}}

#########################################################
###### Read service
#########################################################

GET {{runtimeBaseUrl}}/services/{{serviceName}}
Authorization: {{$aadToken microsoft.com aud:https://tokenvault.azure.net}}
